import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderModel from "./home/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
     

     
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <HeaderModel/>
        <div className="bg-[#0a0e13] min-h-screen relative overflow-hidden">
          
          {/* Gradiente azul topo esquerdo */}
          <div className="absolute top-0 left-0 w-[800px] h-[800px] bg-blue-500/10 rounded-full blur-3xl animate-pulse" />

          {/* Gradiente azul inferior direito */}
          <div className="absolute bottom-0 right-0 w-[600px] h-[600px] bg-cyan-500/5 rounded-full blur-3xl" />
      <main className="relative z-10">
        {children}
      </main>


        </div>
      </body>
    </html>
  );
}
